### ISSUE TITLE
Python version requirement

### ISSUE THREAD

**Issue by kedmenec** [techsmartkids/django-mysql-compressed-fields#1]
Hi I would love to give this library a try to compress some large TextFields we have - unfortunately we are using python 3.8 and this package is defined as supporting python >=3.9,<4.0

```
ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.9,<4.0; 1.0.1 Requires-Python >=3.9,<4.0
```

Just double checking if that is indeed the case, or if its just how the requirement was defined initially?

**Comment by davidfstr** [comment]
I believe only Python 3.9+ has been tested, but I suspect 3.8 would work. This library has no strong dependency on Python.
